version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: seismocluster_db
    environment:
      POSTGRES_DB: SeismoCluster
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5432"
    networks:
      - seismocluster_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d SeismoCluster"]
      interval: 10s
      timeout: 5s
      retries: 5

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: seismocluster_mlflow
    ports:
      - "5000:5000"
    environment:
      MLFLOW_ALLOW_HOSTS: "*"
    volumes:
      - ./backend/mlflow.db:/mlflow/mlflow.db
      - ./backend/mlartifacts:/mlflow/artifacts
    networks:
      - seismocluster_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: seismocluster_backend
    ports:
      - "8000:8000"
    environment:
      DB_NAME: SeismoCluster
      DB_USER: postgres
      DB_PASS: 123456
      DB_HOST: db
      DB_PORT: 5432
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_CLUSTERING_MODEL_NAME: SeismoCluster_Clustering_Model_KMeans
      MLFLOW_HOTSPOT_MODEL_NAME: SeismoCluster_Hotspot_Model
      MLFLOW_ANOMALY_MODEL_NAME: SeismoCluster_Anomaly_Model_ISF
      MLFLOW_HIERARCHY_MODEL_NAME: SeismoCluster_Hierarchy_Model
      PYTHONIOENCODING: utf-8
      LANG: C.UTF-8
    depends_on:
      db:
        condition: service_healthy
      mlflow:
        condition: service_started
    networks:
      - seismocluster_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: seismocluster_frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - seismocluster_net

networks:
  seismocluster_net:
    driver: bridge

volumes:
  postgres_data: