version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: seismocluster_db
    environment:
      POSTGRES_DB: SeismoCluster
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5432"
    networks:
      - seismocluster_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d SeismoCluster"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: seismocluster_backend
    ports:
      - "8000:8000"
    environment:
      DB_NAME: SeismoCluster
      DB_USER: postgres
      DB_PASS: 123456
      DB_HOST: db
      DB_PORT: 5432
      PYTHONIOENCODING: utf-8
      LANG: C.UTF-8
    volumes:
      - ./backend/app/saved_models:/app/app/saved_models
    depends_on:
      db:
        condition: service_healthy
    networks:
      - seismocluster_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: seismocluster_frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - seismocluster_net

networks:
  seismocluster_net:
    driver: bridge

volumes:
  postgres_data: